Properly namespace exception so that the constant can be found
Previously:

```
$ codeclimate analyze -f asdf
error: (NameError) uninitialized constant CC::Analyzer::Formatters::InvalidFormatterError
```

Now:

```
$ codeclimate analyze -f asdf
'asdf' is not a valid formatter. Valid options are: json, text
```